apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argo-role-binding.yaml
- argo-roles.yaml
- namespace.yaml
patches:
 - target:
      name: argo-server
      group: apps
      version: v1
      kind: Deployment
   path: patch-args.yaml
